name: CD for GO Code
on: 
  create:
    tags:
      - v*
      
jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.2
      
      - name: Validate Go Releaser configuration
        uses: docker://goreleaser/goreleaser:latest
        with:
          arg: check
          
      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v3.0.0
        with:
          arg: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
